export default{
    product1:require("../assets/images/product1.webp"),
    product2:require("../assets/images/product2.webp"),
    product3:require("../assets/images/product3.webp"),
    product4:require("../assets/images/product4.webp"),
    product5:require("../assets/images/product5.webp"),
    product6:require("../assets/images/product6.webp"),
    product7:require("../assets/images/product7.webp"),
    product8:require("../assets/images/product8.webp"),
    banner2 : require("../assets/images/banner-02.jpg"),
    banner3 : require("../assets/images/banner-07.jpg"),
    banner4 : require("../assets/images/banner-08.jpg"),
    banner5 : require("../assets/images/banner.webp"),
    bgVideo : require("../assets/images/bg-video-01.jpg.webp"),
    blog1: require("../assets/images/blog-01.jpg"),
    blog2 : require("../assets/images/blog-02.jpg"),
    blog3 : require("../assets/images/blog-03.jpg"),
    carousel1 : require("../assets/images/carousel1.jpg"),
    carousel2 : require("../assets/images//carousel2.jpg"),
    carousel3 : require("../assets/images/carousel3.webp"),
    discover : require("../assets/images/discover.png.webp"),
    express: require("../assets/images/express.png.webp"),
    gallery1 : require("../assets/images/gallery-03.jpg"),
    gallery2 : require("../assets/images/gallery-07.jpg"),
    gallery3 : require("../assets/images/gallery-09.jpg"),
    gallery4 : require("../assets/images/gallery-13.jpg"),
    gallery5 : require("../assets/images/gallery-15.jpg"),
    item1 : require("../assets/images/item-02.jpg"),
    item2 : require("../assets/images/item-03.jpg"),
    item3 : require("../assets/images/item-05.jpg"),
    item4 : require("../assets/images/item-07.jpg"),
    itemcart1 : require("../assets/images/item-cart-01.jpg"),
    itemcart2 : require("../assets/images/item-cart-02.jpg"),
    itemcart3 : require("../assets/images/item-cart-03.jpg"),
    logo : require("../assets/images/logo.png.webp"),
    paypal : require("../assets/images/paypal.png.webp"),
    shop : require("../assets/images/shop-item-09.jpg"),
    shopp:require("../assets/images/shop-item-09-removebg-preview.png"),
    visa : require("../assets/images/visa.png.webp"),
    about:require("../assets/images/about1.webp")
}